### ISSUE TITLE
Pinned requirements versions.

### ISSUE THREAD

**Issue by ficinator** [ondewo/ondewo-logging-python#1]
## Current Behavior

Is it really necessary to have the package versions so specific?

```
fluent-logger==0.9.6
msgpack
python_dotenv==0.10.1
PyYAML==5.3.1
```

## Desired Behavior

Relax the issues as much as possible so logging still works and does not limit other modules to such a specific versions.

**Comment by FergusFettes** [comment]
for some reason fluentd asked for pinned requirements, but i don't think there is any good reason for it.
